# Generated by Django 5.2.1 on 2025-05-16 10:32

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, db_index=True, help_text='Vector representation of the analysis text.', max_length=1024, null=True)),
                ('financial_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_analysis', to='core.financialstatement')),
            ],
        ),
    ]
