# Generated by Django 5.2.1 on 2025-05-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportanalysis',
            name='last_modified',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
