# Generated by Django 5.2.1 on 2025-05-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0002_financialreportanalysis_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportanalysis',
            name='analysis_text',
            field=models.TextField(blank=True, help_text='The generated analysis text that was embedded.', null=True),
        ),
    ]
