# Generated by Django 5.2.1 on 2025-05-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enable_pgvector'),
        ('embeds', '0003_financialreportanalysis_analysis_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreportanalysis',
            name='financial_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_report_analysis', to='core.financialstatement'),
        ),
    ]
