# Generated by Django 5.2.1 on 2025-05-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enable_pgvector'),
        ('embeds', '0005_remove_financialreportanalysis_financial_report_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReportAnalysis',
            new_name='FinancialStatementAnalysis',
        ),
    ]
