# Generated by Django 5.2.1 on 2025-05-16 15:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeds', '0006_rename_financialreportanalysis_financialstatementanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementanalysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, help_text='Vector representation of the analysis text.', max_length=1024, null=True),
        ),
    ]
