# Generated by Django 5.2.1 on 2025-05-09 08:23

from django.db import migrations

CURRENCIES = [
    {"code": "USD", "name": "US Dollar", "symbol": "$"},
    {"code": "EUR", "name": "Euro", "symbol": "€"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥"},
    {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥"},
    {"code": "AUD", "name": "Australian Dollar", "symbol": "A$"},
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "C$"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "Fr"},
    {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "HK$"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "S$"},
]


def create_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.bulk_create(
        [
            Currency(
                code=currency["code"],
                name=currency["name"],
                symbol=currency["symbol"],
            )
            for currency in CURRENCIES
        ]
    )


def remove_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.filter(
        code__in=[currency["code"] for currency in CURRENCIES]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_currency"),
    ]

    operations = [migrations.RunPython(create_currencies, remove_currencies)]
