# Generated by Django 5.2.1 on 2025-05-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField()),
                ('calendar_year', models.IntegerField()),
                ('period', models.CharField(db_comment='For example: "Q1", "Q2", "Q3", "Q4", "FY"', max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_income', models.DecimalField(decimal_places=2, max_digits=20)),
                ('income_before_tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cash_and_equivalents', models.DecimalField(decimal_places=2, max_digits=20)),
                ('research_and_development_expenses', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
        ),
    ]
