# Generated by Django 5.2.1 on 2025-05-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_cik_alter_financialstatement_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDataTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_financial_report_fetch', models.DateField(null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_tracker', to='core.company')),
            ],
        ),
    ]
