# Generated by Django 5.2.1 on 2025-05-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companydatatracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='cash_and_equivalents',
        ),
    ]
