# Generated by Django 5.2.1 on 2025-05-12 12:12

from django.db import migrations

CURRENCIES = [
    {"code": "USD", "name": "US Dollar", "symbol": "$"},
    {"code": "EUR", "name": "Euro", "symbol": "€"},
    {"code": "JPY", "name": "Japanese Yen", "symbol": "¥"},
    {"code": "GBP", "name": "British Pound Sterling", "symbol": "£"},
    {"code": "AUD", "name": "Australian Dollar", "symbol": "A$"},
    {"code": "CAD", "name": "Canadian Dollar", "symbol": "C$"},
    {"code": "CHF", "name": "Swiss Franc", "symbol": "Fr"},
    {"code": "CNY", "name": "Chinese Yuan", "symbol": "¥"},
    {"code": "HKD", "name": "Hong Kong Dollar", "symbol": "HK$"},
    {"code": "INR", "name": "Indian Rupee", "symbol": "₹"},
    {"code": "MXN", "name": "Mexican Peso", "symbol": "$"},
    {"code": "SGD", "name": "Singapore Dollar", "symbol": "S$"},
    {"code": "NZD", "name": "New Zealand Dollar", "symbol": "NZ$"},
    {"code": "SEK", "name": "Swedish Krona", "symbol": "kr"},
    {"code": "KRW", "name": "South Korean Won", "symbol": "₩"},
    {"code": "NOK", "name": "Norwegian Krone", "symbol": "kr"},
    {"code": "BRL", "name": "Brazilian Real", "symbol": "R$"},
    {"code": "ZAR", "name": "South African Rand", "symbol": "R"},
    {"code": "RUB", "name": "Russian Ruble", "symbol": "₽"},
    {"code": "TRY", "name": "Turkish Lira", "symbol": "₺"},
    {"code": "DKK", "name": "Danish Krone", "symbol": "kr"},
    {"code": "PLN", "name": "Polish Złoty", "symbol": "zł"},
    {"code": "THB", "name": "Thai Baht", "symbol": "฿"},
    {"code": "IDR", "name": "Indonesian Rupiah", "symbol": "Rp"},
    {"code": "HUF", "name": "Hungarian Forint", "symbol": "Ft"},
    {"code": "CZK", "name": "Czech Koruna", "symbol": "Kč"},
    {"code": "ILS", "name": "Israeli New Shekel", "symbol": "₪"},
    {"code": "CLP", "name": "Chilean Peso", "symbol": "$"},
    {"code": "PHP", "name": "Philippine Peso", "symbol": "₱"},
    {"code": "AED", "name": "United Arab Emirates Dirham", "symbol": "د.إ"},
    {"code": "COP", "name": "Colombian Peso", "symbol": "$"},
    {"code": "SAR", "name": "Saudi Riyal", "symbol": "﷼"},
    {"code": "MYR", "name": "Malaysian Ringgit", "symbol": "RM"},
    {"code": "RON", "name": "Romanian Leu", "symbol": "lei"},
    {"code": "BGN", "name": "Bulgarian Lev", "symbol": "лв"},
    {"code": "ARS", "name": "Argentine Peso", "symbol": "$"},
    {"code": "VND", "name": "Vietnamese Dong", "symbol": "₫"},
    {"code": "UAH", "name": "Ukrainian Hryvnia", "symbol": "₴"},
    {"code": "NGN", "name": "Nigerian Naira", "symbol": "₦"},
    {"code": "PKR", "name": "Pakistani Rupee", "symbol": "₨"},
    {"code": "EGP", "name": "Egyptian Pound", "symbol": "E£"},
    {"code": "PEN", "name": "Peruvian Sol", "symbol": "S/"},
    {"code": "TWD", "name": "New Taiwan Dollar", "symbol": "NT$"},
    {"code": "HRK", "name": "Croatian Kuna", "symbol": "kn"},
    {"code": "MAD", "name": "Moroccan Dirham", "symbol": "د.م."},
    {"code": "QAR", "name": "Qatari Riyal", "symbol": "﷼"},
    {"code": "KWD", "name": "Kuwaiti Dinar", "symbol": "د.ك"},
    {"code": "BHD", "name": "Bahraini Dinar", "symbol": ".د.ب"},
    {"code": "OMR", "name": "Omani Rial", "symbol": "﷼"},
    {"code": "JOD", "name": "Jordanian Dinar", "symbol": "د.ا"},
]


def create_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.bulk_create(
        [
            Currency(
                code=currency["code"],
                name=currency["name"],
                symbol=currency["symbol"],
            )
            for currency in CURRENCIES
        ],
        ignore_conflicts=True,
    )


def remove_currencies(apps, schema_editor):
    Currency = apps.get_model("core", "Currency")
    Currency.objects.filter(
        code__in=[currency["code"] for currency in CURRENCIES]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_financialstatement_cash_and_equivalents"),
    ]

    operations = [migrations.RunPython(create_currencies, remove_currencies)]
