# Generated by Django 5.2.1 on 2025-05-14 05:16

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_rest_of_currencies"),
    ]

    operations = [VectorExtension()]
